### ISSUE TITLE
enable multiple WS

### ISSUE THREAD

**Issue by fuwafuwacat** [effective-reversi-dev/effective_reversi#57]
Saga.jsがうまく機能していないみたいで、WSが複数走らなくなっている模様。原因を調査し、修正する。

**Comment by polestar1592** [comment]
Mergeしたのち、部屋選択画面作成中実際に複数のwebsocketが必要になったので、
そこで動確しました。
無事動いているようです。
一応 @fuwafuwacat が立ててくれたので、問題なければ閉じちゃってください!
