### ISSUE TITLE
【Game】Change warning message at modal

### ISSUE THREAD

**Issue by fuwafuwacat** [effective-reversi-dev/effective_reversi#83]
観戦者については部屋から出るときに出すモーダルの文言を変える（この部屋で対戦が始まっていたらもう戻れませんよ、的な言葉）

**Comment by polestar1592** [comment]
プレイヤーと観戦者で共通の一つのメッセージにしちゃえば良いかも
観戦者は～...
プレイヤーは～...

**Comment by fuwafuwacat** [comment]
ご対応ありがとうございました。クローズします。
